name: SimpleSpawner
main: xenialdan\SimpleSpawner\Loader
version: 1.3.4
api: [1.0.0, 2.0.0, 3.0.0, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 4.0.0]
load: POSTWORLD
author: XenialDan

permissions:
  simplespawner:
    description: Perm for giving spawner
    default: op
